include ../Makefile.variable

all: debug_tool.o draw_dot.o

debug_tool.o: debug_tool.cpp
	$(CC) $(CFLAGS) $(INCLUDE) $(I_VINE) -c debug_tool.cpp
	
draw_dot.o: draw_dot.cpp
	$(CC) $(CFLAGS) $(INCLUDE) $(I_VINE) -c draw_dot.cpp
	